### ISSUE TITLE
Add a test case for using the metal_lb to provide LoadBalancer service to the test runc deployment

### ISSUE THREAD

**Issue by mcastelino** [clearlinux/cloud-native-setup#108]
```
apiVersion: v1
kind: Service
metadata:
  name: php-apache-runc-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: php-apache-runc
  sessionAffinity: None
  type: LoadBalancer
```
