### ISSUE TITLE
Add test case to create nginx-ingress with metal-lb provided IP

### ISSUE THREAD

**Issue by mcastelino** [clearlinux/cloud-native-setup#109]
This allows the http gateway to be directly exposed on well known ports to the rest of the network.
```
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx

---
```
