### ISSUE TITLE
scripts (or k8s) presume to use first ethernet controller

### ISSUE THREAD

**Issue by grahamwhaley** [clearlinux/cloud-native-setup#12]
I think, by default, the scripts will set up the k8s network hung off the first ether controller on the master node.
In my case, that is not correct - I have two ether cards, and my node pool is hung off the second one.

I'll see if I can figure out what needs to be told to use the second (or rather, a specific) network controller to talk to the nodes. If anybody wants to chip in with some input, please do :-)

**Comment by grahamwhaley** [comment]
To note. I'm running the setup scripts on a bare metal Clear Linux cluster btw, not in the vagrant VM setup.

**Comment by grahamwhaley** [comment]
From https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#initializing-your-master
I probably need to:
> --apiserver-advertise-address=<ip-address> argument to kubeadm init

as by default `kubeadm` picks the interface with the default gateway on it, and for me that is not the nic with the nodes on.
Do we need to add support to the script command line for this, or are we happy leaving it up to the user to modify to their needs?

**Comment by grahamwhaley** [comment]
I'm having trouble getting this to work yet.
I have a feeling maybe the ability to put this in the yaml init file was only added in 1.13.
See:
https://github.com/kubernetes/kubernetes/pull/70761

I've tried adding in the option like:

```yaml
apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
nodeRegistration:
  criSocket: /var/run/crio/crio.sock
  #localAPIEndpoint:
  #aPIEndpoint:
APIEndpoint:
  advertiseAddress: "192.168.xxx.yyy"
  bindPort: 6443
---
```

to the `kubeadm.yaml` with both the three different section name types (`APIEndpoint` and the two commented out), but no luck - I still end up with the IP address of my primary ether port.

I'm going to see if I can edit my `~/.kube/config` and edit the cluster server IP address there and re-start the script part way through....

Any input/help appreciated here ;-)

**Comment by ganeshmaharaj** [comment]
@grahamwhaley yes, that is a thing that @mcastelino and i have observed and was something that we were discussing as well as that affects my vagrant setup too. we thought of settign it as an env variable that a user can set which the script can read and then add the necessary bits to `kubeadm init`.

**Comment by grahamwhaley** [comment]
grr, I tried to hack the IP into the kube config, but the cert is encoded to the IP address, so it nacked it....
sigh. So, looking for input on how to fix this in the kubeinit.yaml....

**Comment by krsna1729** [comment]
@grahamwhaley
```
apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
nodeRegistration:
  criSocket: /var/run/crio/crio.sock
apiEndpoint:
  advertiseAddress: "192.52.100.11"
  bindPort: 6443
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
featureGates:
  RuntimeClass: true
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: v1.12.0
controlPlaneEndpoint: "192.52.100.11:6443"
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
apiServerExtraArgs:
  advertise-address: "192.52.100.11"
  feature-gates: RuntimeClass=true
```
But the join did not work

```
[discovery] Trying to connect to API Server "192.52.100.11:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://192.52.100.11:6443"
[discovery] Failed to request cluster info, will try again: [Get https://192.52.100.11:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: net/http: TLS handshake timeout]
[discovery] Failed to request cluster info, will try again: [Get https://192.52.100.11:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: net/http: TLS handshake timeout]
```
