### ISSUE TITLE
Add support for firecracker 

### ISSUE THREAD

**Issue by mcastelino** [clearlinux/cloud-native-setup#23]
Clearlinux now supports and bundles firecracker. Add support for adding firecracker as an additional runtime class in kata. This allows runc, kata with qemu and kata with firecracker to live alongside each other in the same cluster on all nodes

Add a new script along the lines of `setup_firecracker.sh`

```
#!/bin/bash

cat <<EOT | tee /etc/kata-containers/configuration_firecracker.toml

[hypervisor.firecracker]
path = "/usr/bin/firecracker"
kernel = "/usr//share/kata-containers/vmlinux.container"
image = "/usr//share/kata-containers/kata-containers.img"
kernel_params = ""
default_vcpus = 1
default_memory = 4096
default_maxvcpus = 0
default_bridges = 1
block_device_driver = "virtio-mmio"
disable_block_device_use = false
enable_debug = true
use_vsock = true

[shim.kata]
path = "/usr//libexec/kata-containers/kata-shim"

[runtime]
internetworking_model="tcfilter"
EOT

cat <<EOT | tee /usr/bin/kata-runtime-fire
#!/bin/bash

/usr/bin/kata-runtime --kata-config /etc/kata-containers/configuration_firecracker.toml "$@"
EOT

mkdir -p /etc/crio/
cp /usr/share/defaults/crio/crio.conf /etc/crio/crio.conf

echo -e "\n[crio.runtime.runtimes.kata]\nruntime_path = \"/usr/bin/kata-runtime\"" >> /etc/crio/crio.conf
echo -e "\n[crio.runtime.runtimes.fire]\nruntime_path = \"/usr/bin/kata-runtime-fire\"" >> /etc/crio/crio.conf

sed -i 's|\(\[crio\.runtime\]\)|\1\nmanage_network_ns_lifecycle = true|' /etc/crio/crio.conf

sed -i 's/storage_driver = \"overlay\"/storage_driver = \"devicemapper\"\
storage_option = [\
  \"dm.basesize=8G\",\
  \"dm.directlvm_device=\/dev\/vdb\",\
  \"dm.directlvm_device_force=true\",\
  \"dm.fs=ext4\"\
]/g' /etc/crio/crio.conf


systemctl daemon-reload
systemctl restart crio
```

And a simple test case along the lines of `tests/test-deploy-fire.yaml`

```
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    run: php-apache-fire
  name: php-apache-fire
spec:
  replicas: 1
  selector:
    matchLabels:
      run: php-apache-fire
  template:
    metadata:
      labels:
        run: php-apache-fire
    spec:
      runtimeClassName: fire
      containers:
      - image: k8s.gcr.io/hpa-example
        imagePullPolicy: Always
        name: php-apache
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 200m
      restartPolicy: Always
---
apiVersion: v1 
kind: Service
metadata:
  name: php-apache-fire
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: php-apache-fire
  sessionAffinity: None
  type: ClusterIP
```
