### ISSUE TITLE
kata-deploy causing cri-o to fail after node is up

### ISSUE THREAD

**Issue by amshinde** [clearlinux/cloud-native-setup#64]
kata-deploy adds multiple entries for the kata-runtime in /etc/crio/crio.conf, after the node is up.
This causes cri-o to fail causing the node state to show as `Not-ready`.
For running any further pods, I needed to manually remove the duplicate entries from the crio conf file, stop the kata-deploy ds and restart cri-o.

**Comment by amshinde** [comment]
See https://github.com/kata-containers/packaging/issues/374

**Comment by amshinde** [comment]
cc @krsna1729 @egernst

**Comment by ganeshmaharaj** [comment]
@amshinde didn't https://github.com/kata-containers/packaging/pull/334 fix that issue? that patch was intended for that particular issue.

**Comment by krsna1729** [comment]
@ganeshmaharaj you fixed it for network namespace lifecycle. Same needs to be done for everything we modify in kata-deploy :P

**Comment by ganeshmaharaj** [comment]
@krsna1729 yeah, just realized that. Will try and get that fixed out.

**Comment by grahamwhaley** [comment]
just fyi, whilst I can see it, @ganeshmaharaj - I just ran up your Ubuntu vagrant, and used `create_stack.sh minimal`. I was just checking if crio was up (related to #73 ), and did:

```bash
$ systemctl status crio
 * crio.service - Open Container Initiative Daemon
   Loaded: loaded (/lib/systemd/system/crio.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-03-20 06:46:55 PDT; 3min 55s ago
     Docs: https://github.com/kubernetes-sigs/cri-o
  Process: 11651 ExecStart=/usr/bin/crio $CRIO_STORAGE_OPTIONS $CRIO_NETWORK_OPTIONS $CRIO_METRICS_OPTION
 Main PID: 11651 (code=exited, status=1/FAILURE)

... last key parsed 'crio.runtime.runtimes'): Key 'crio.runtime.runtimes.kata-qemu' has already been defined.
...
```

Having a look in `/etc/crio/crio.conf`:

```toml
# Path to directory where CNI plugin binaries are located.
plugin_dir = "/opt/cni/bin"
[crio.runtime.runtimes.kata-qemu]
  runtime_path = "/opt/kata/bin/kata-qemu"

[crio.runtime.runtimes.kata-fc]
  runtime_path = "/opt/kata/bin/kata-fc"
[crio.runtime.runtimes.kata-qemu]
  runtime_path = "/opt/kata/bin/kata-qemu"

[crio.runtime.runtimes.kata-fc]
  runtime_path = "/opt/kata/bin/kata-fc"
```

which feels like this issue does it? Deleting those last duplicate lines and `systemctl restart crio` gets the crio service back up.
